services:
  - type: web
    name: smartconnect-pesapal-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    pythonVersion: 3.11
    startCommand: gunicorn config.wsgi:application
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: smartconnect-db
          property: internalConnectionString
    postDeploy:
      - python manage.py migrate